-- Pan Kotecki — produkty startowe (wygenerowane z lib/products.ts).
-- Wklej w Supabase SQL Editor i uruchom (wymaga wcześniej seed.sql z kategoriami).

insert into products
  (slug, name, category_id, price_grosze, short_description, description, details, badges, bestseller, in_stock, sort_order)
values
('mysz-fela', 'Mysz na sznurku „Fela”', (select id from categories where slug = 'zabawki'), 2400, 'Klasyk, którego żaden kot nie ignoruje.', 'Miękka mysz z naturalnym sznurkiem i szczyptą kocimiętki w środku. Lekka, idealnie wyważona do podrzucania i łapania. Sprawdza się w samotnej zabawie i w pojedynku z wędką.', ARRAY['Wymiary: 7 cm + 20 cm sznurek', 'Wypełnienie z kocimiętką', 'Materiał: filc i bawełna']::text[], ARRAY['Bestseller']::text[], true, true, 1),
('wedka-lowca', 'Wędka z piórkiem „Łowca”', (select id from categories where slug = 'zabawki'), 3900, 'Wyzwala instynkt łowcy w trzy sekundy.', 'Elastyczny pręt, długa linka i piórka, które tańczą przy najmniejszym ruchu. Stworzona do wspólnej zabawy, która rozrusza nawet leniwego kanapowca.', ARRAY['Długość pręta: 45 cm', 'Wymienne piórka', 'Antypoślizgowy uchwyt']::text[], '{}'::text[], true, true, 2),
('pilki-dzwoneczek', 'Piłki z dzwoneczkiem (3-pak)', (select id from categories where slug = 'zabawki'), 1900, 'Trzy kolory, jeden cel — gonić.', 'Lekkie, ażurowe piłki z dzwoneczkiem w środku. Toczą się nieprzewidywalnie po podłodze i potrafią zająć kota na długie minuty.', ARRAY['3 sztuki', 'Średnica: 4 cm', 'Cichy dzwoneczek']::text[], '{}'::text[], false, true, 3),
('tunel-jaskinia', 'Tunel składany „Jaskinia”', (select id from categories where slug = 'zabawki'), 8900, 'Kryjówka, zasadzka i tor wyścigowy w jednym.', 'Składany tunel z szeleszczącą warstwą i okienkiem do zaczepek. Rozkłada się w sekundę, a po zabawie chowa na płasko. Łączy się z innymi tunelami w cały labirynt.', ARRAY['Długość: 90 cm', 'Składany, na płasko', 'Szeleszcząca wyściółka']::text[], '{}'::text[], true, true, 4),
('kopak-kocimietka', 'Kopak z kocimiętką „Banan”', (select id from categories where slug = 'zabawki'), 2900, 'Do przytulania, kopania i obejmowania łapami.', 'Wydłużony kopak wypełniony kocimiętką, w sam raz do chwytania przednimi łapami i młócenia tylnymi. Klasyczna forma zabawy, która rozładowuje kocią energię.', ARRAY['Długość: 23 cm', 'Naturalna kocimiętka', 'Wytrzymały szew']::text[], '{}'::text[], false, true, 5),
('legowisko-chmurka', 'Legowisko „Chmurka”', (select id from categories where slug = 'akcesoria'), 15900, 'Miękkie gniazdo, z którego nie chce się wychodzić.', 'Okrągłe legowisko z wysokim, miękkim rantem dającym poczucie bezpieczeństwa. Wyjmowana poduszka, przyjemny w dotyku materiał i dno antypoślizgowe.', ARRAY['Średnica: 50 cm', 'Zdejmowana poszewka', 'Pranie w 30°C']::text[], ARRAY['Bestseller']::text[], true, true, 6),
('miska-lapka', 'Miska ceramiczna „Łapka”', (select id from categories where slug = 'akcesoria'), 4900, 'Płytka miska, która szanuje kocie wąsy.', 'Szeroka, niska miska z wypalanej ceramiki — bez podrażniania wąsów. Stabilna podstawa i powierzchnia łatwa do utrzymania w czystości.', ARRAY['Pojemność: 250 ml', 'Ceramika szkliwiona', 'Można myć w zmywarce']::text[], '{}'::text[], false, true, 7),
('fontanna-zrodlo', 'Fontanna do picia „Źródło”', (select id from categories where slug = 'akcesoria'), 19900, 'Świeża, krążąca woda zachęca do picia.', 'Cicha fontanna z filtrem, która utrzymuje wodę w ruchu i świeżości. Delikatny szum zachęca kota do częstszego picia — wsparcie dla nerek i nawodnienia.', ARRAY['Pojemność: 2 l', 'Cichy silnik', 'Filtr węglowy w zestawie']::text[], '{}'::text[], true, true, 8),
('drapak-wieza', 'Drapak słupek „Wieża”', (select id from categories where slug = 'akcesoria'), 21900, 'Punkt widokowy i drapak w jednym.', 'Stabilny słupek owinięty sizalem, zwieńczony platformą do obserwacji świata. Ratuje kanapę i daje kotu jego własne, wysokie miejsce.', ARRAY['Wysokość: 80 cm', 'Naturalny sizal', 'Stabilna podstawa']::text[], '{}'::text[], false, true, 9),
('obroza-dzwonek', 'Obroża z zawieszką „Dzwonek”', (select id from categories where slug = 'akcesoria'), 3500, 'Bezpieczne zapięcie, miejsce na adresówkę.', 'Miękka obroża z zapięciem bezpieczeństwa, które puszcza pod naciskiem. Regulowana, z zawieszką na adres i dyskretnym dzwoneczkiem.', ARRAY['Regulacja: 20–30 cm', 'Zapięcie bezpieczeństwa', 'Miejsce na adresówkę']::text[], '{}'::text[], false, true, 10),
('transporter-wyprawa', 'Transporter „Wyprawa”', (select id from categories where slug = 'akcesoria'), 14900, 'Spokojna podróż do weterynarza i dalej.', 'Lekki, dobrze wentylowany transporter z miękkim wnętrzem i pewnym zapięciem. Górne otwarcie ułatwia wkładanie nieprzekonanego pasażera.', ARRAY['Do 7 kg', 'Wentylacja z trzech stron', 'Składany']::text[], '{}'::text[], false, true, 11),
('szczotka-wyczesujaca', 'Szczotka wyczesująca „Gładko”', (select id from categories where slug = 'akcesoria'), 3900, 'Mniej sierści na kanapie, więcej na szczotce.', 'Szczotka z chowanymi zębami — jednym kliknięciem usuwasz zebraną sierść. Delikatna dla skóry, skuteczna w usuwaniu martwego podszerstka.', ARRAY['Chowane zęby', 'Ergonomiczny uchwyt', 'Do każdej długości włosa']::text[], '{}'::text[], false, true, 12),
('kubek-poranny-mruczek', 'Kubek „Poranny Mruczek”', (select id from categories where slug = 'kubki'), 5900, 'Pierwsza kawa i kot na parapecie.', 'Pojemny kubek z grubej ceramiki z minimalistycznym kocim motywem. Przyjemny w dłoni, długo trzyma ciepło. Do kawy, herbaty i porannego wpatrywania się w okno.', ARRAY['Pojemność: 350 ml', 'Ceramika', 'Można myć w zmywarce']::text[], ARRAY['Bestseller']::text[], true, true, 13),
('kubek-termiczny-w-drodze', 'Kubek termiczny „W drodze”', (select id from categories where slug = 'kubki'), 8900, 'Ciepła kawa przez całą poranną trasę.', 'Stalowy kubek termiczny z izolacją próżniową i szczelnym wieczkiem. Utrzymuje temperaturę godzinami i mieści się w uchwycie samochodowym.', ARRAY['Pojemność: 450 ml', 'Stal nierdzewna', 'Szczelne wieczko']::text[], '{}'::text[], false, true, 14),
('kubki-on-i-kot', 'Zestaw 2 kubki „On i Kot”', (select id from categories where slug = 'kubki'), 9900, 'Dwa kubki, jedna wspólna poranna rutyna.', 'Para kubków w spójnym, minimalnym stylu — jeden dla Ciebie, drugi dla wielbiciela kotów obok. Świetny pomysł na prezent.', ARRAY['2 sztuki po 300 ml', 'Ceramika', 'W pudełku prezentowym']::text[], '{}'::text[], false, true, 15),
('torba-crazy-cat', 'Torba płócienna „Crazy Cat”', (select id from categories where slug = 'dla-wlasciciela'), 4500, 'Zakupy, książki i koci manifest na ramieniu.', 'Mocna bawełniana torba z minimalnym nadrukiem. Długie ucha, pojemne wnętrze i charakter, który mówi wszystko bez słów.', ARRAY['Bawełna 280 g/m²', 'Wymiary: 38 × 42 cm', 'Długie ucha']::text[], '{}'::text[], true, true, 16),
('skarpetki-lapki', 'Skarpetki „Łapki” (2-pak)', (select id from categories where slug = 'dla-wlasciciela'), 2900, 'Kocie łapki na Twoich stopach.', 'Miękkie, oddychające skarpetki z dyskretnym motywem łapek. Dwie pary w pudełku — dla siebie albo na prezent.', ARRAY['2 pary', 'Bawełna z domieszką elastanu', 'Rozmiar uniwersalny 38–43']::text[], '{}'::text[], false, true, 17),
('przypinka-kot', 'Przypinka emaliowana „Kot”', (select id from categories where slug = 'dla-wlasciciela'), 1900, 'Mały detal, wielka deklaracja.', 'Emaliowana przypinka z sylwetką kota i mocnym zapięciem motylkowym. Idealna na kurtkę, plecak albo płócienną torbę.', ARRAY['Wymiary: 2,5 cm', 'Twarda emalia', 'Zapięcie motylkowe']::text[], '{}'::text[], false, true, 18),
('notes-dziennik-kota', 'Notes „Dziennik Kota”', (select id from categories where slug = 'dla-wlasciciela'), 3500, 'Na notatki, plany i kocie obserwacje.', 'Notes w twardej oprawie z gładkim papierem i wstążką-zakładką. Minimalna okładka z kocim akcentem. Leży płasko po otwarciu.', ARRAY['Format A5', '192 strony', 'Gumka i zakładka']::text[], '{}'::text[], false, true, 19),
('bluza-mow-do-kota', 'Bluza „Mów do kota”', (select id from categories where slug = 'dla-wlasciciela'), 15900, 'Miękka bluza dla zespołu „kot ważniejszy”.', 'Ciężka, miękka w środku bluza z kapturem i drobnym haftem. Krój oversize, materiał, z którego nie chce się wychodzić — zupełnie jak kot z legowiska.', ARRAY['Bawełna z pętelką 320 g/m²', 'Krój oversize', 'Rozmiary S–XXL']::text[], '{}'::text[], false, true, 20)
on conflict (slug) do nothing;
